=== Abonia1/xml-Tuto/Postal/data.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT utilisateurs_adresses (adresse+)>
<!ELEMENT adresse (numero, nom_de_rue, complement?, code_postal, ville, region, pays)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT nom_de_rue (#PCDATA)>
<!ELEMENT complement (#PCDATA)>
<!ELEMENT code_postal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT pays (#PCDATA)>

<!ATTLIST adresse
type CDATA #REQUIRED
>
<!ATTLIST nom_de_rue
  type_de_voie CDATA #REQUIRED
>

=== Abonia1/xml-Tuto/Postal/data.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE utilisateurs_adresses SYSTEM "data.dtd">

<utilisateurs_adresses>
  <adresse type="domicile">
    <numero>8</numero>
    <nom_de_rue type_de_voie="rue">Changarnier</nom_de_rue>
    <complement></complement>
    <code_postal>75012</code_postal>
    <ville>Paris</ville>
    <region>Ile de france</region>
    <pays>France</pays>
  </adresse>
  <adresse type="entreprise">
    <numero>29</numero>
    <nom_de_rue type_de_voie="rue">du docteur heulin</nom_de_rue>
    <complement>Batiment B</complement>
    <code_postal>75017</code_postal>
    <ville>Paris</ville>
    <region>Ile de France</region>
    <pays>France</pays>
  </adresse>
</utilisateurs_adresses>
